# Generated by Django 4.0.4 on 2022-05-17 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipperreceiver',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ShipperReceiver', serialize=False, to='deliveryapp.order'),
        ),
    ]
