# Generated by Django 4.0.4 on 2022-05-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryapp', '0002_alter_user_options_alter_user_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='CCCD',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
