# Generated by Django 4.0.4 on 2022-05-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryapp', '0002_auctionhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipperreceiver',
            name='price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
