# Generated by Django 4.0.4 on 2022-05-12 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryapp', '0003_alter_shipperreceiver_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionhistory',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='deliveryapp.order'),
        ),
    ]
