# Generated by Django 4.0.4 on 2022-05-17 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryapp', '0004_rename_order_name_order_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='order_name',
        ),
    ]
